/* GET_<>_DATA_ACTION - dispatch when you start the download
§ <>_DATA_RECEIVED_ACTION - dispatch when you receive the data
§ <>_DATA_ERROR_ACTION - dispatch when you receive an error */

export const POPULAR_DATA_ACTION = 'POPULAR_DATA_ACTION';
export const POPULAR_DATA_RECEIVED_ACTION = 'POPULAR_DATA_RECEIVED_ACTION';
export const POPULAR_DATA_ERROR_ACTION = 'POPULAR_DATA_ERROR_ACTION';

export const CATEGORY_DATA_ACTION = 'CATEGORY_DATA_ACTION';
export const CATEGORY_DATA_RECEIVED_ACTION = 'CATEGORY_DATA_RECEIVED_ACTION';
export const CATEGORY_DATA_ERROR_ACTION = 'CATEGORY_DATA_ERROR_ACTION';

export const MOVIES_BY_CATEGORY_DATA_ACTION = 'MOVIES_BY_CATEGORY_DATA_ACTION';
export const MOVIES_BY_CATEGORY_DATA_RECEIVED_ACTION = 'MOVIES_BY_CATEGORY_DATA_RECEIVED_ACTION';
export const MOVIES_BY_CATEGORY_DATA_ERROR_ACTION = 'MOVIES_BY_CATEGORY_DATA_ERROR_ACTION';

export const ASSET_BY_ID_DATA_ACTION = 'ASSET_BY_ID_DATA_ACTION';
export const ASSET_BY_ID_DATA_RECEIVED_ACTION = 'ASSET_BY_ID_DATA_RECEIVED_ACTION';
export const ASSET_BY_ID_DATA_ERROR_ACTION = 'ASSET_BY_ID_DATA_ERROR_ACTION';

export const VIDEO_DATA_ACTION = 'VIDEO_DATA_ACTION';
export const VIDEO_DATA_RECEIVED_ACTION = 'VIDEO_DATA_RECEIVED_ACTION';
export const VIDEO_DATA_ERROR_ACTION = 'VIDEO_DATA_ERROR_ACTION';